services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=papirfly'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '54320:5432'
