spring:
  application:
    name: papirfly
  flyway:
    baselineOnMigrate: true
    enabled: true

  datasource:
    url: "jdbc:postgresql://localhost:54320/papirfly" # points to docker image from compose.yml
    username: "postgres"
    password: "postgres"


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/swagger-ui.html