spring:
  application:
    name: papirfly
  flyway:
    baselineOnMigrate: true
    enabled: true

  datasource:
    url: "jdbc:postgresql://localhost:5432/papirfly"
    username: "postgres"
    password: "postgres"


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/swagger-ui.html